In [1]:
#Shopping Discount:
import numpy as np
prices = np.array([800, 1200, 950, 1500, 2000])
discount = prices[prices > 1000]
print("Products Eligible for Discount:")
print(discount)

Products Eligible for Discount:
[1200 1500 2000]


In [2]:
#Random data generation - weather forecast:
temperature = np.random.randint(25, 41, 7)
print("Weekly Temperature:")
print(temperature)

Weekly Temperature:
[31 27 37 29 29 25 29]


In [3]:
# sorting- employee salary ranking:
salary = np.array([45000, 30000, 55000, 40000])
sorted_salary = np.sort(salary)
print(sorted_salary)

[30000 40000 45000 55000]


In [5]:
sales = np.array([8500, 6200, 9100, 7400, 5600])
print("Sorted Sales:")
print(np.sort(sales))

Sorted Sales:
[5600 6200 7400 8500 9100]


In [4]:
#Reshape - Class room Arrangement:
students = np.arange(1, 21)
seating = students.reshape(4, 5)
print(seating)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [6]:
passengers = np.arange(1, 31)
seats = passengers.reshape(6, 5)
print(seats)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [7]:
# Matrix Multiplication:
units = np.array([[120],
                  [180],
                  [150]])
cost = 8
bill = units * cost
print("Electricity Bill:")
print(bill)

Electricity Bill:
[[ 960]
 [1440]
 [1200]]
