In [2]:
import numpy as np
print("Multiplication matrix:")
p1 = np.array([[3,4],[5,6]])
p2 = np .array([[4,5],[8,9]])
print(np.dot(p1,p2))


[[44 51]
 [68 79]]


In [3]:
print(p1 @ p2)

[[44 51]
 [68 79]]


In [5]:
print("Transpose of matrix:")
print(p1.T)
print(p2.T)

Transpose of matrix:
[[3 5]
 [4 6]]
[[4 8]
 [5 9]]


In [6]:
print("Random matrix:")
matrix = np.random.randint(1, 100, (3, 3))print("Random Matrix:")
print(matrix)

Random matrix:
[[ 6 69 66]
 [90 47 74]
 [60 12 31]]


In [10]:
print("Random - Toss a Coin :")
Coin = np.random.choice(["Head","Tail"])
print(Coin)

Random - Toss a Coin :
Tail


In [12]:
print("Random - Dice Roll:")
dice = np.random.randint(1, 7)
print("Dice Roll:", dice)

Random - Dice Roll:
Dice Roll: 1


In [13]:
r1 = np.array([1,2,3])
r2 = np.array([4,5,6])
print("vstack-veritcal stack:")
print(np.vstack((r1,r2)))

vstack-veritcal stack:
[[1 2 3]
 [4 5 6]]


In [14]:
print("hstack-Horizontal Stack:")
print(np.hstack((r1,r2)))

hstack-Horizontal Stack:
[1 2 3 4 5 6]


In [16]:
print("Concatenate- Joins two or more arrays:")
print(np.concatenate((r1, r2)))

Concatenate- Joins two or more arrays:
[1 2 3 4 5 6]


In [19]:
print("split-divides a array into smaller array & arange-evenly spaced array:")
print(np.split(np.arange(12), 4))

split-divides a array into smaller array & arange-evenly spaced array:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]


In [25]:
print("unsorted to sorted array:")
employee = np.array([11,12,13,14,15,16,12,14,15,17])
print(np.sort(employee))

unsorted to sorted array:
[11 12 12 13 14 14 15 15 16 17]


In [27]:
print("argsort-index order")
print(np.argsort(employee))

argsort-index order
[0 1 6 2 3 7 4 8 5 9]


In [28]:
print("Employee number greater then 12:")
print(np.where(employee>12))

Employee number greater then 12:
(array([2, 3, 4, 5, 7, 8, 9]),)


In [31]:
empsalary = np.array([10000,30000,50000,25000,15000])
Emi =empsalary>=15000
print("Emi Debited:")
print(Emi)
print("Emp salary Debited:")
print(empsalary[Emi])


Emi Debited:
[False  True  True  True  True]
Emp salary Debited:
[30000 50000 25000 15000]
