In [1]:
import numpy as np
print("Storing Employee's Salary in 1D and 2D Array:")
p = np.array([3000,5000,4000,2000])
r = np.array([[1000,2000,3000],[4000,5000,6000]])
print(p)
print(r)

Storing Employee's Salary in 1D and 2D Array:
[3000 5000 4000 2000]
[[1000 2000 3000]
 [4000 5000 6000]]


In [7]:
print("Reshape - Change the Shape(Dimensions) without changing its data:")
employee = np.array([100,101,102,103,104,105])
reshaped = employee.reshape(6,1)
print(reshaped)

Reshape - Change the Shape(Dimensions) without changing its data:
[[100]
 [101]
 [102]
 [103]
 [104]
 [105]]


In [10]:
print("converts the original array into row by row:")
flat = r.flatten()
print(flat)

converts the original array into row by row:
[1000 2000 3000 4000 5000 6000]


In [11]:
raveled = r.ravel()
print(raveled)

[1000 2000 3000 4000 5000 6000]


In [13]:
print("Arithmetic operations:")
x = np.array([6,7,8,9])
y = np.array([1,2,3,5])
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x**2)

Arithmetic operations:
[ 7  9 11 14]
[5 5 5 4]
[ 6 14 24 45]
[6.         3.5        2.66666667 1.8       ]
[36 49 64 81]


In [16]:
print("A array with different shapes are automatical expands a smaller array:")
matrix = np.array([[11,12,13,14], [15,16,17,18]])
vector = np.array([40,50,60,70])

print(matrix + vector)

A array with different shapes are automatical expands a smaller array:
[[51 62 73 84]
 [55 66 77 88]]


In [17]:
print("Aggregation Function:")
print(matrix.sum())
print(matrix.mean())
print(np.median(matrix))
print(matrix.std())
print(matrix.var())
print(matrix.min())
print(matrix.max())
print(matrix.sum(axis=0))
print(matrix.sum(axis=1))

Aggregation Function:
116
14.5
14.5
2.29128784747792
5.25
11
18
[26 28 30 32]
[50 66]
