In [1]:
#vstack- combine sales data from two stores
import numpy as np
store_A = np.array([1200, 1500, 1800])
store_B = np.array([1400, 1600, 1700])
sales = np.vstack((store_A, store_B))
print("Store A Sales:", store_A)
print("Store B Sales:", store_B)
print("\nCombined Sales Report")
print(sales)

Store A Sales: [1200 1500 1800]
Store B Sales: [1400 1600 1700]

Combined Sales Report
[[1200 1500 1800]
 [1400 1600 1700]]


In [2]:
#hstack - combine employees id and name
employee_ids = np.array([101, 102, 103])
department_codes = np.array([10, 20, 30])
employee_data = np.hstack((employee_ids, department_codes))
print("Combined Employee Data:")
print(employee_data)


Combined Employee Data:
[101 102 103  10  20  30]


In [3]:
#concatenate - combine monthly expenses
january = np.array([5000, 7000, 6000])
february = np.array([6500, 7200, 5800])
expenses = np.concatenate((january, february))
print("All Expenses:")
print(expenses)

All Expenses:
[5000 7000 6000 6500 7200 5800]


In [4]:
#split - students into two batches:
students = np.array([1,2,3,4,5,6,7,8,9,10])
batch1, batch2 = np.split(students, 2)
print("Batch 1:", batch1)
print("Batch 2:", batch2)

Batch 1: [1 2 3 4 5]
Batch 2: [ 6  7  8  9 10]


In [ ]:
#arange
