In [2]:
import numpy as np
print("Storing Employee's Salary in 1D and 2D Array:")
p = np.array([3000,5000,4000,2000])
r = np.array([[1000,2000,3000],[4000,5000,6000]])
print(p)
print(r)


Storing Employee's Salary in 1D and 2D Array:
[3000 5000 4000 2000]
[[1000 2000 3000]
 [4000 5000 6000]]


In [11]:
print("Creats a empty array filled with 0:")
p = np.zeros((3,3))
print(p)

Creats a empty array filled with 0:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
print("An array Filled with 1:")
ones = np.ones((3,3))
print(ones)

An array Filled with 1:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
print("Creating an identity matrix:")
identity = np.eye(3)
print(identity)

Creating an identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
print("Even space between the values:")
ar = np.arange(0,10,2)
print(ar)

Even space between the values:
[0 2 4 6 8]


In [21]:
print("Evenly spaces 5 values:")
lin = np.linspace(0,1,5)
print(lin)

Evenly spaces 5 values:
[0.   0.25 0.5  0.75 1.  ]


In [23]:
print("Attributes that describe its shape,no of dimensions,total number of elements and its data type:")
print(r.shape)
print(r.ndim)
print(r.size)
print(r.dtype)

Attributes that describe its shape,no of dimensions,total number of elements and its data type:
(2, 3)
2
6
int64


In [27]:
print("Indexing and slicing in array:")
print(r[0, 1])

2000


In [30]:
print(" It returns entire column 2 values:")
print(r[:, 2])


[3000 6000]


In [35]:
print("It returns entire  row 1 values:")
print(r[1, :])

It returns entire  row 1 values:
[4000 5000 6000]


In [36]:
print("It returns row 0,1 and column 0,1 values:")
print(r[0:2, 0:2])

It returns row 0,1 and column 0,1 values:
[[1000 2000]
 [4000 5000]]
